import docker from "./docker.svg";
import postgresssql from "./elephant.png";
import git from "./Git-Icon-1788C.svg";
import go from "./go.svg";
import mongodb from "./mongodb.svg";
import mysql from "./mysql.svg";
import nextjs from "./nextjs-transparent.svg";
import nodejs from "./nodejs.svg";

import css from "./css.svg";
import react from "./react.svg";
import redis from "./redis-logo-full-color-rgb.svg";
import redux from "./redux.svg";
import html from "./html.svg";
import socketio from "./Socket-io.svg";
import tailwind from "./tailwind.svg";
import ts from "./ts.svg";
import vercel from "./vercel.svg";
import express from "./express.svg";
export { express,go, git, postgresssql, html, redis, mongodb, mysql, socketio, nextjs, nodejs, react, redux, tailwind, ts, vercel, docker, css };
